---
- name: Install Samba-package
  apt:
    name: [ 'samba' ]
    state: present
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
  become: yes



- name: Add Samba-Group to admin-users
  user:
    name: "{{ item.name }}"
    groups: sambashare
    append: yes
  ignore_errors: yes
  become: yes
  with_items:
    - "{{ admin_users }}"
